# using in-memory h2 so it  donesn't need to provision a local database instance
spring.datasource.url=jdbc:h2:mem:petstoredb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# force hibernate to only validate so liquibase remains the strict source of truth for schema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# keep the redirect strictly relative
server.tomcat.use-relative-redirects=true